<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    $viewModel = $block->getData('view_model');
  
    if(!$_category) return;
    $imageUrl = $viewModel->getCategoryImage($_category->getData('entity_id'));
    if ($_imgUrl = $imageUrl) {
        $_imgHtml = '<div class="category-breadcrumbs-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image breadcrumbs-image" /></div>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'breadcrumbs_image');
        /* @escapeNotVerified */ echo $_imgHtml;
    }
?>
